version: '3.5'
services:
  redis:
    image: redis
    ports:
      - 6379:6379/tcp 
    container_name: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-admin:
    container_name: redis-admin
    image: rediscommander/redis-commander
    working_dir: /redis-commander/bin
    links: 
      - redis
    ports:
      - 8081:8081/tcp
    environment:
      - host=redis
      - password=foobared
      - db=0
    command: sh -c "/usr/local/bin/redis-commander --redis-host $$host --redis-password $$password --redis-db 0" 